# Generated by Django 3.1.1 on 2020-10-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20201010_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
