# Generated by Django 3.2.5 on 2021-07-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
    ]
