# Generated by Django 3.2.5 on 2021-07-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_book_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
        ),
    ]
