# Generated by Django 3.2.5 on 2021-07-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_book_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=0, max_length=200),
        ),
    ]
