# Generated by Django 3.2.5 on 2021-07-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
